### ISSUE TITLE
회원가입 API 작성

### ISSUE THREAD

**Issue by Dokuny** [Dokuny/DoraDora#1]
## Description
아래의 사항을 지켜 회원가입 API를 작성해야 합니다.

### 준수 사항
- [x]  User는 회원가입을 할 수 있습니다.
- [x]  회원가입 시 입력한 회원정보를 DB에 저장합니다.

### 주의 사항

- [x]  이미 회원가입된 이메일로 회원가입을 할 수 없습니다.

## Todo
- [x] 회원가입 API 작성

## ETC
작은 단위로 커밋하도록 합시다.

**Comment by Dokuny** [comment]
회원가입 API 구현이 완료되었기에 이슈를 닫습니다.
